global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Create a job for Docker daemons.
  - job_name: 'docker'
    dockerswarm_sd_configs:
      - host: tcp://tasks.dockersocat:2375
        role: nodes
    relabel_configs:
      # Fetch metrics on port 9323.
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      # Set hostname as instance label
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
      # Only keep manager nodes
      - source_labels: [__meta_dockerswarm_role]
        regex: manager
        action: keep

  # Create a job for Docker Swarm containers.
  - job_name: 'dockerswarm'
    dockerswarm_sd_configs:
      - host: tcp://tasks.dockersocat:2375
        role: tasks
    relabel_configs:
      # Only keep containers that should be running.
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        regex: .+
        action: keep
      # Only keep container that are attached to metrics_net.
      - source_labels: [__meta_dockerswarm_network_name]
        regex: metrics_net
        action: keep
      # Get metrics port from `prometheus-port` label
      - source_labels: [__address__, __meta_dockerswarm_service_label_prometheus_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      # Get metrics path from `prometheus-path` label
      - source_labels: [__meta_dockerswarm_service_label_prometheus_path]
        action: replace
        replacement: $1
        target_label: __metrics_path__
      # Add node label to job
      - source_labels: [__meta_dockerswarm_node_hostname]
        replacement: $1
        target_label: node
      # Use the task labels that are prefixed by `prometheus-`.
      - regex: __meta_dockerswarm_service_label_prometheus_(.+)
        action: labelmap
        replacement: $1